drivers: scsi: ufs-mediatek: add missing function prototype
../drivers/scsi/ufs/ufs-mediatek.c:110:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct rpmb_dev *ufs_mtk_rpmb_get_raw_dev()
                                         ^
                                          void
1 error generated.

Change-Id: I6abcb7e9156ffe6da3e30498b49f0097b3041e9a
Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>